sudo: false
language: python
python:
- '3.5'
matrix:
  allow_failures:
  - env: TOXENV=py35-djangodev-sqlite
  - env: TOXENV=py35-djangodev-mysql
  - env: TOXENV=py35-djangodev-postgresql
  - env: TOXENV=py35-django110-mysql
env:
  matrix:
  - TOXENV=py27-django111-sqlite
  - TOXENV=py35-django111-sqlite
  - TOXENV=py35-django20-sqlite
  - TOXENV=py35-djangodev-sqlite
  - TOXENV=py35-djangodev-mysql
  - TOXENV=py35-djangodev-postgresql
  - TOXENV=checkqa
  - TOXENV=docs
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
